name: dnetty
description: Dart Netty
version: 0.0.1
author: YanhxCN <yanhxcn@gmail.com>
homepage: https://github.com/YanhxCN/dnetty

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: